### ISSUE TITLE
Implement Open API standards on endpoints

### ISSUE THREAD

**Issue by adamclark-dev** [comicrelief/grants-api-serverless#10]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

**Comment by pvhee** [comment]
@adamclark-dev we might want to consider going directly with 3.0 ([rc2 was released 5 days ago](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.0.0-rc2)). Here is an interesting review from gov.uk: https://github.com/alphagov/open-standards/issues/31
