### ISSUE TITLE
Remove duplicates

### ISSUE THREAD

**Issue by pvhee** [comicrelief/grants-api-serverless#11]
We have many similar grants that are duplicates, except for a (possibly flawed) grant identifier. Find out a way to remove dupes to make the results unique.

**Comment by adamclark-dev** [comment]
@pvhee If we md5 the following fields `name, start date and amount, country code` prior to putting the data into ElasticSearch then we can filter duplicates at the ElasticSearch query.

**Comment by pvhee** [comment]
Was going to remove grant_id and throw them into a `Set` to avoid losing data before it goes to ES as a first trial, but filtering this before it goes into ES would be a better solution long-term, after we've found out the issues with the ids

**Comment by adamclark-dev** [comment]
ES is currently using `grants_project_id` as index id, so will need to change if removing `grants_project_id` at parser level?

**Comment by pvhee** [comment]
Thinking about it, it might be cleaner to deal with any of this within https://github.com/comicrelief/cubs-grants-parser? I'll make sure to keep `grants_project_id` so we don't have to change anything here.

**Comment by pvhee** [comment]
Handled via https://github.com/comicrelief/cubs-grants-parser version 0.0.4 or above
