### ISSUE TITLE
Remove /es/consume endpoint

### ISSUE THREAD

**Issue by pvhee** [comicrelief/grants-api-serverless#7]
I think having it available via sls cli should be enough for testing purposes?

**Comment by pvhee** [comment]
We can have the API automatically consume CUBS after every production deployment instead (via Concourse), and remove the http endpoint. What do you think @adamclark-dev ?

**Comment by adamclark-dev** [comment]
@pvhee am thinking about making the endpoint private with a key assigned by concourse, we can then use that API key via concourse to consume on every deploy, as you suggested. What do you think?

**Comment by pvhee** [comment]
Sounds good, but I wouldn't keep the consumption method via http though as it'll time out eventually. Much better done via CLI so no need to deal with http at all?

**Comment by adamclark-dev** [comment]
Makes sense, will do.
